repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.287'
    hooks:
      - id: ruff
        args: [
          "--line-length=120",
          "--fix",
          "--exit-non-zero-on-fix",
          "."
        ]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [
          '--profile=black',
          '--line-length=120',
          '--multi-line=3',
          '--trailing-comma'
        ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [ python ]
        args: [
          '--ignore-missing-imports'
        ]
