repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.287'
    hooks:
      - id: ruff
        args: [ "--fix", "--exit-non-zero-on-fix", "." ]
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [ python ]
        pass_filenames: true
        args: [
          '--profile=black',
          '--line-length=120',
          '--multi-line=3',
          '--trailing-comma'
        ]

      - id: black
        name: black
        entry: black
        language: python
        types: [ python ]
        pass_filenames: true
        args: [
          '--line-length=120',
          '--target-version=py311',
          '--skip-string-normalization',
        ]

      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [ python ]
        args: [
          '--ignore-missing-imports'
        ]
