version: "3.9"

services:
  app:
    build: .
    volumes:
      - static_value:/zoo_store/app/static/
      - media_value:/zoo_store/app/media/
      - ./zoo_store:/app
    command: >
      bash -c "
      python manage.py makemigrations && 
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    env_file:
      - ./.env
    ports:
      - "8000:8000"

volumes:
  static_value:
  media_value: